In [173]:
# Import dependencies
import pandas as pd
import numpy as np
from datetime import datetime
from re import search

In [174]:
# Files to load
agentstate_to_load = "Working_Folder/Final_Project/call_center_data_2021/Agent_State_Summary_Hourly_2021.csv"
notready_to_load = "Working_Folder/Final_Project/call_center_data_2021/Agent_Not_Ready_Detail_2021.csv"
calltype_to_load = "Working_Folder/Final_Project/call_center_data_2021/Call_Type_Historical_Fields_Hourly_2021.csv"

## Clean Agent State Summary file

In [175]:
# Load Agent State Summary 
Agent_State_Summary_df = pd.read_csv(agentstate_to_load)
Agent_State_Summary_df

,Agent_ID,Date,Hour,GROUP_NAME,CALLS_ANSWERED,INTERNAL_CALS,EXTERNAL_OUTGOING_CALLS,RONA,LOGGED_ON_TIME,AVAILABLE_TIME,...,EXT_OUT_CALLS_TALK_TIME,AVG_TALK_TIME_EXTERNAL,HOLD_TIME,PER_HOLD,INTERNAL_CALLS_TIME,AVG_TALK_TIME_INTERNAL,PER_INTERNAL,HANDLED_CALLS_TIME,AVG_HANDLE_TIME,BUSY_OTHER_TIME
0,8,1/4/21,8:00 AM,CN_SCH_SPECC_POD_1_SG,4,0,0,0,0:28:48,0:14:24,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:14:24,0:00:00,0:00:00
1,8,1/4/21,8:00 AM,CN_SCH_SPECC_SP_POD_1_SG,0,0,0,0,0:28:48,0:14:24,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0:14:24
2,8,1/4/21,8:00 AM,SCH_CCM01.Cisco_Voice.defa.72419,0,0,2,0,0:28:48,0:14:24,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0:14:24
3,3,1/4/21,8:00 AM,CN_SCH_SPECC_EN_SG,3,2,0,0,0:28:48,0:14:24,...,0:00:00,0:00:00,0:00:00,5.22%,0:00:00,0:00:00,2.32%,0:14:24,0:00:00,0:00:00
4,3,1/4/21,8:00 AM,CN_SCH_SPECC_SP_SG,1,2,0,0,0:28:48,0:14:24,...,0:00:00,0:00:00,0:00:00,0.11%,0:00:00,0:00:00,0.68%,0:00:00,0:00:00,0:14:24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88428,17,12/30/21,4:00 PM,CN_SCH_SPECC_SP_SG,0,0,0,0,0:57:36,0:43:12,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0:14:24
88429,17,12/30/21,4:00 PM,SCH_CCM01.Cisco_Voice.defa.72419,0,0,0,0,0:57:36,0:43:12,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0:14:24
88430,17,12/30/21,5:00 PM,CN_SCH_SPECC_EN_SG,0,0,0,0,0:00:00,0:00:00,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0:00:00
88431,17,12/30/21,5:00 PM,CN_SCH_SPECC_SP_SG,0,0,0,0,0:00:00,0:00:00,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0:00:00
88432,17,12/30/21,5:00 PM,SCH_CCM01.Cisco_Voice.defa.72419,0,0,0,0,0:00:00,0:00:00,...,0:00:00,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0.00%,0:00:00,0:00:00,0:00:00

### Remove unnecessary columns

In [176]:
# Show column names for easier copy/paste for column removal
Agent_State_Summary_df.columns

Index(['Agent_ID', 'Date', 'Hour', 'GROUP_NAME', 'CALLS_ANSWERED',
       'INTERNAL_CALS', 'EXTERNAL_OUTGOING_CALLS', 'RONA', 'LOGGED_ON_TIME',
       'AVAILABLE_TIME', 'PER_AVAIL', 'NOT_READY', 'PER_NOT_READY',
       'WORK_TIME', 'PER_WORK_TIME', 'TALK_TIME', 'PER_TALK_TIME',
       'HANDLED_CALLS_TALK_TIME', 'AVG_TALK_TIME', 'TALK_TIME_OUT',
       'PER_TALK_TIME_OUT', 'EXT_OUT_CALLS_TALK_TIME',
       'AVG_TALK_TIME_EXTERNAL', 'HOLD_TIME', 'PER_HOLD',
       'INTERNAL_CALLS_TIME', 'AVG_TALK_TIME_INTERNAL', 'PER_INTERNAL',
       'HANDLED_CALLS_TIME', 'AVG_HANDLE_TIME', 'BUSY_OTHER_TIME'],
      dtype='object')

In [177]:
# Remove unnecessary columns
Agent_State_Summary_df.drop(columns = ['INTERNAL_CALS', 'EXTERNAL_OUTGOING_CALLS',
        'NOT_READY', 'PER_NOT_READY', 'WORK_TIME', 'PER_WORK_TIME', 'TALK_TIME',
        'PER_TALK_TIME','AVG_TALK_TIME', 'TALK_TIME_OUT', 'PER_TALK_TIME_OUT',
        'HANDLED_CALLS_TALK_TIME', 'EXT_OUT_CALLS_TALK_TIME', 'AVG_TALK_TIME_EXTERNAL',
        'HOLD_TIME', 'PER_HOLD', 'INTERNAL_CALLS_TIME', 'AVG_TALK_TIME_INTERNAL',
        'PER_INTERNAL', 'BUSY_OTHER_TIME'], inplace=True)
Agent_State_Summary_df

,Agent_ID,Date,Hour,GROUP_NAME,CALLS_ANSWERED,RONA,LOGGED_ON_TIME,AVAILABLE_TIME,PER_AVAIL,HANDLED_CALLS_TIME,AVG_HANDLE_TIME
0,8,1/4/21,8:00 AM,CN_SCH_SPECC_POD_1_SG,4,0,0:28:48,0:14:24,57.52%,0:14:24,0:00:00
1,8,1/4/21,8:00 AM,CN_SCH_SPECC_SP_POD_1_SG,0,0,0:28:48,0:14:24,57.52%,0:00:00,0:00:00
2,8,1/4/21,8:00 AM,SCH_CCM01.Cisco_Voice.defa.72419,0,0,0:28:48,0:14:24,57.52%,0:00:00,0:00:00
3,3,1/4/21,8:00 AM,CN_SCH_SPECC_EN_SG,3,0,0:28:48,0:14:24,40.08%,0:14:24,0:00:00
4,3,1/4/21,8:00 AM,CN_SCH_SPECC_SP_SG,1,0,0:28:48,0:14:24,40.08%,0:00:00,0:00:00
...,...,...,...,...,...,...,...,...,...,...,...
88428,17,12/30/21,4:00 PM,CN_SCH_SPECC_SP_SG,0,0,0:57:36,0:43:12,74.86%,0:00:00,0:00:00
88429,17,12/30/21,4:00 PM,SCH_CCM01.Cisco_Voice.defa.72419,0,0,0:57:36,0:43:12,74.86%,0:00:00,0:00:00
88430,17,12/30/21,5:00 PM,CN_SCH_SPECC_EN_SG,0,0,0:00:00,0:00:00,61.54%,0:00:00,0:00:00
88431,17,12/30/21,5:00 PM,CN_SCH_SPECC_SP_SG,0,0,0:00:00,0:00:00,61.54%,0:00:00,0:00:00
88432,17,12/30/21,5:00 PM,SCH_CCM01.Cisco_Voice.defa.72419,0,0,0:00:00,0:00:00,61.54%,0:00:00,0:00:00

### Remove values not associated with a POD

In [178]:
# Check group name values
Agent_State_Summary_df['GROUP_NAME'].value_counts()

SCH_CCM01.Cisco_Voice.defa.72419    25297
CN_SCH_SPECC_EN_SG                  13438
CN_SCH_SPECC_SP_SG                  10076
CN_SCH_SPECC_POD_2_SG                9749
CN_SCH_SPECC_POD_1_SG                8951
CN_SCH_SPECC_SP_POD_2_SG             8294
CN_SCH_SPECC_SP_POD_1_SG             7630
SCH_ONC_OVF_SG                       4998
Name: GROUP_NAME, dtype: int64

In [179]:
# Remove values not associated with a POD
Agent_State_Summary_df = Agent_State_Summary_df.loc[(Agent_State_Summary_df['GROUP_NAME'] !=
          'SCH_CCM01.Cisco_Voice.defa.72419') & (Agent_State_Summary_df['GROUP_NAME'] != 'SCH_ONC_OVF_SG')]

In [180]:
# Check group name values
Agent_State_Summary_df['GROUP_NAME'].value_counts()

CN_SCH_SPECC_EN_SG          13438
CN_SCH_SPECC_SP_SG          10076
CN_SCH_SPECC_POD_2_SG        9749
CN_SCH_SPECC_POD_1_SG        8951
CN_SCH_SPECC_SP_POD_2_SG     8294
CN_SCH_SPECC_SP_POD_1_SG     7630
Name: GROUP_NAME, dtype: int64

In [181]:
# Check that hours are between 8AM to 5PM
Agent_State_Summary_df['Hour'].value_counts()

9:00 AM     6246
1:00 PM     6212
11:00 AM    6189
12:00 PM    6181
10:00 AM    6145
2:00 PM     5868
4:00 PM     5628
3:00 PM     5625
8:00 AM     4992
5:00 PM     4093
7:00 AM      692
6:00 PM       65
10:00 PM      18
11:00 PM      18
8:00 PM       18
9:00 PM       18
7:00 PM       18
12:00 AM      16
1:00 AM       16
2:00 AM       16
3:00 AM       16
4:00 AM       16
5:00 AM       16
6:00 AM       16
Name: Hour, dtype: int64

In [182]:
# Remove hours outside of working hours (8AM to 5PM)
Agent_State_Summary_df = Agent_State_Summary_df.loc[(Agent_State_Summary_df['Hour'] != '6:00 PM')
            & (Agent_State_Summary_df['Hour'] != '7:00 PM') & (Agent_State_Summary_df['Hour'] != '8:00 PM')
            & (Agent_State_Summary_df['Hour'] != '9:00 PM')& (Agent_State_Summary_df['Hour'] != '10:00 PM')
            & (Agent_State_Summary_df['Hour'] != '11:00 PM') & (Agent_State_Summary_df['Hour'] != '12:00 AM')
            & (Agent_State_Summary_df['Hour'] != '1:00 AM') & (Agent_State_Summary_df['Hour'] != '2:00 AM')
            & (Agent_State_Summary_df['Hour'] != '3:00 AM') & (Agent_State_Summary_df['Hour'] != '4:00 AM')
            & (Agent_State_Summary_df['Hour'] != '5:00 AM') & (Agent_State_Summary_df['Hour'] != '6:00 AM')
            & (Agent_State_Summary_df['Hour'] != '7:00 AM')]
Agent_State_Summary_df['Hour'].value_counts()

9:00 AM     6246
1:00 PM     6212
11:00 AM    6189
12:00 PM    6181
10:00 AM    6145
2:00 PM     5868
4:00 PM     5628
3:00 PM     5625
8:00 AM     4992
5:00 PM     4093
Name: Hour, dtype: int64

### Group by pod

In [183]:
# Create a function
def pod_name(x):
    if (x == 'CN_SCH_SPECC_EN_SG') or (x == 'CN_SCH_SPECC_SP_SG'):
        return 'POD 3'
    elif (x == 'CN_SCH_SPECC_POD_2_SG') or (x == 'CN_SCH_SPECC_SP_POD_2_SG'):
        return 'POD 2'
    else:
        return 'POD 1'

# Create new column to assign values
Agent_State_Summary_df['POD_NAME'] = Agent_State_Summary_df['GROUP_NAME'].apply(pod_name)
Agent_State_Summary_df

,Agent_ID,Date,Hour,GROUP_NAME,CALLS_ANSWERED,RONA,LOGGED_ON_TIME,AVAILABLE_TIME,PER_AVAIL,HANDLED_CALLS_TIME,AVG_HANDLE_TIME,POD_NAME
0,8,1/4/21,8:00 AM,CN_SCH_SPECC_POD_1_SG,4,0,0:28:48,0:14:24,57.52%,0:14:24,0:00:00,POD 1
1,8,1/4/21,8:00 AM,CN_SCH_SPECC_SP_POD_1_SG,0,0,0:28:48,0:14:24,57.52%,0:00:00,0:00:00,POD 1
3,3,1/4/21,8:00 AM,CN_SCH_SPECC_EN_SG,3,0,0:28:48,0:14:24,40.08%,0:14:24,0:00:00,POD 3
4,3,1/4/21,8:00 AM,CN_SCH_SPECC_SP_SG,1,0,0:28:48,0:14:24,40.08%,0:00:00,0:00:00,POD 3
6,4,1/4/21,8:00 AM,CN_SCH_SPECC_POD_2_SG,4,0,0:28:48,0:14:24,36.40%,0:14:24,0:00:00,POD 2
...,...,...,...,...,...,...,...,...,...,...,...,...
88425,17,12/30/21,3:00 PM,CN_SCH_SPECC_SP_SG,0,0,0:57:36,0:28:48,57.83%,0:00:00,0:00:00,POD 3
88427,17,12/30/21,4:00 PM,CN_SCH_SPECC_EN_SG,4,0,0:57:36,0:43:12,74.86%,0:14:24,0:00:00,POD 3
88428,17,12/30/21,4:00 PM,CN_SCH_SPECC_SP_SG,0,0,0:57:36,0:43:12,74.86%,0:00:00,0:00:00,POD 3
88430,17,12/30/21,5:00 PM,CN_SCH_SPECC_EN_SG,0,0,0:00:00,0:00:00,61.54%,0:00:00,0:00:00,POD 3
88431,17,12/30/21,5:00 PM,CN_SCH_SPECC_SP_SG,0,0,0:00:00,0:00:00,61.54%,0:00:00,0:00:00,POD 3

In [184]:
# Check pods
Agent_State_Summary_df['POD_NAME'].value_counts()

POD 3    23414
POD 2    17621
POD 1    16144
Name: POD_NAME, dtype: int64

### Change dtypes

In [185]:
# Check dtypes
print(Agent_State_Summary_df.dtypes)

Agent_ID               int64
Date                  object
Hour                  object
GROUP_NAME            object
CALLS_ANSWERED         int64
RONA                   int64
LOGGED_ON_TIME        object
AVAILABLE_TIME        object
PER_AVAIL             object
HANDLED_CALLS_TIME    object
AVG_HANDLE_TIME       object
POD_NAME              object
dtype: object

In [186]:
# Change dtypes
Agent_State_Summary_df['Date'] = Agent_State_Summary_df['Date'].astype('string')
Agent_State_Summary_df['Date'] = pd.to_datetime(Agent_State_Summary_df['Date'])
Agent_State_Summary_df['GROUP_NAME'] = Agent_State_Summary_df['GROUP_NAME'].astype('string')
Agent_State_Summary_df['PER_AVAIL'] = Agent_State_Summary_df['PER_AVAIL'].str.rstrip('%').astype('float') / 100.0
Agent_State_Summary_df['POD_NAME'] = Agent_State_Summary_df['POD_NAME'].astype('string')


# Change Hour am/pm time to only show hour in military time
Agent_State_Summary_df['Hour'] = pd.to_datetime(Agent_State_Summary_df['Hour'], format='%I:%M %p').dt.strftime('%H')


# Change LOGGED_ON_TIME hh:mm:ss format to seconds
def get_seconds(time_str):
    hh, mm, ss = time_str.split(':')
    return int(hh) * 3600 + int(mm) * 60 + int(ss)

Agent_State_Summary_df['LOGGED_ON_TIME'] = Agent_State_Summary_df['LOGGED_ON_TIME'].astype('string')
Agent_State_Summary_df['LOGGED_ON_TIME'] = Agent_State_Summary_df['AVAILABLE_TIME'].apply(get_seconds)


# Change AVAILABLE_TIME hh:mm:ss format to seconds
Agent_State_Summary_df['AVAILABLE_TIME'] = Agent_State_Summary_df['AVAILABLE_TIME'].astype('string')
Agent_State_Summary_df['AVAILABLE_TIME'] = Agent_State_Summary_df['AVAILABLE_TIME'].apply(get_seconds)


# Change HANDLED_CALLS_TIME hh:mm:ss format to seconds
Agent_State_Summary_df['HANDLED_CALLS_TIME'] = Agent_State_Summary_df['HANDLED_CALLS_TIME'].astype('string')
Agent_State_Summary_df['HANDLED_CALLS_TIME'] = Agent_State_Summary_df['HANDLED_CALLS_TIME'].apply(get_seconds)


# Change AVG_HANDLE_TIME hh:mm:ss format to seconds
Agent_State_Summary_df['AVG_HANDLE_TIME'] = Agent_State_Summary_df['AVG_HANDLE_TIME'].astype('string')
Agent_State_Summary_df['AVG_HANDLE_TIME'] = Agent_State_Summary_df['AVG_HANDLE_TIME'].apply(get_seconds)


print(Agent_State_Summary_df.dtypes)
Agent_State_Summary_df

Agent_ID                       int64
Date                  datetime64[ns]
Hour                          object
GROUP_NAME                    string
CALLS_ANSWERED                 int64
RONA                           int64
LOGGED_ON_TIME                 int64
AVAILABLE_TIME                 int64
PER_AVAIL                    float64
HANDLED_CALLS_TIME             int64
AVG_HANDLE_TIME                int64
POD_NAME                      string
dtype: object

,Agent_ID,Date,Hour,GROUP_NAME,CALLS_ANSWERED,RONA,LOGGED_ON_TIME,AVAILABLE_TIME,PER_AVAIL,HANDLED_CALLS_TIME,AVG_HANDLE_TIME,POD_NAME
0,8,2021-01-04,08,CN_SCH_SPECC_POD_1_SG,4,0,864,864,0.5752,864,0,POD 1
1,8,2021-01-04,08,CN_SCH_SPECC_SP_POD_1_SG,0,0,864,864,0.5752,0,0,POD 1
3,3,2021-01-04,08,CN_SCH_SPECC_EN_SG,3,0,864,864,0.4008,864,0,POD 3
4,3,2021-01-04,08,CN_SCH_SPECC_SP_SG,1,0,864,864,0.4008,0,0,POD 3
6,4,2021-01-04,08,CN_SCH_SPECC_POD_2_SG,4,0,864,864,0.3640,864,0,POD 2
...,...,...,...,...,...,...,...,...,...,...,...,...
88425,17,2021-12-30,15,CN_SCH_SPECC_SP_SG,0,0,1728,1728,0.5783,0,0,POD 3
88427,17,2021-12-30,16,CN_SCH_SPECC_EN_SG,4,0,2592,2592,0.7486,864,0,POD 3
88428,17,2021-12-30,16,CN_SCH_SPECC_SP_SG,0,0,2592,2592,0.7486,0,0,POD 3
88430,17,2021-12-30,17,CN_SCH_SPECC_EN_SG,0,0,0,0,0.6154,0,0,POD 3
88431,17,2021-12-30,17,CN_SCH_SPECC_SP_SG,0,0,0,0,0.6154,0,0,POD 3

### Export dataframe to CSV

In [187]:
Agent_State_Summary_df.to_csv('Data/Clean_Agent_State_Summary_2021.csv', index=False)

## Clean Agent Not Ready file

In [188]:
# Read file into dataframe
Not_Ready_df = pd.read_csv(notready_to_load)
Not_Ready_df

,Agent_ID,LOG_ON_DATE_TIME,LOG_ON_DURATION,REASON_CODE,DURATION,LOG_ON_DUR_PER,TOTAL_TIME_NOT_READU,NOT_READY_PER
0,11,1/4/21 7:47,8:24:00,Break[10003],6:52:00,1.35%,21:38:00,8.40%
1,11,1/4/21 7:47,8:24:00,Extended Wrap Up[10048],1:43:00,0.34%,21:38:00,2.10%
2,11,1/4/21 7:47,8:24:00,Go To Logout[10025],0:05:00,0.02%,21:38:00,0.10%
3,11,1/4/21 7:47,8:24:00,Lunch[10001],59:50:00,11.79%,21:38:00,73.30%
4,11,1/4/21 7:47,8:24:00,Undefined[0],13:08:00,2.59%,21:38:00,16.10%
...,...,...,...,...,...,...,...,...
18472,16,12/30/21 8:00,0:00:00,Extended Wrap Up[10048],1:51:00,0.44%,21:10:00,2.30%
18473,16,12/30/21 8:00,0:00:00,Go To Logout[10025],0:02:00,0.01%,21:10:00,0.00%
18474,16,12/30/21 8:00,0:00:00,Lunch[10001],0:31:00,14.41%,21:10:00,74.60%
18475,16,12/30/21 8:00,0:00:00,Outbound Calls[32],0:38:00,0.15%,21:10:00,0.80%
18476,16,12/30/21 8:00,0:00:00,Undefined[0],0:56:00,0.22%,21:10:00,1.20%

### Remove unnecessary columns

In [189]:
# Show column names for easier copy/paste for column removal
Not_Ready_df.columns

Index(['Agent_ID', 'LOG_ON_DATE_TIME', 'LOG_ON_DURATION', 'REASON_CODE',
       'DURATION', 'LOG_ON_DUR_PER', 'TOTAL_TIME_NOT_READU', 'NOT_READY_PER'],
      dtype='object')

In [190]:
# Remove unnecessary columns
Not_Ready_df = Not_Ready_df.drop(columns = ['LOG_ON_DURATION','LOG_ON_DUR_PER', 'TOTAL_TIME_NOT_READU', 'NOT_READY_PER'])
Not_Ready_df

       Agent_ID LOG_ON_DATE_TIME              REASON_CODE  DURATION
0            11      1/4/21 7:47             Break[10003]   6:52:00
1            11      1/4/21 7:47  Extended Wrap Up[10048]   1:43:00
2            11      1/4/21 7:47      Go To Logout[10025]   0:05:00
3            11      1/4/21 7:47             Lunch[10001]  59:50:00
4            11      1/4/21 7:47             Undefined[0]  13:08:00
...         ...              ...                      ...       ...
18472        16    12/30/21 8:00  Extended Wrap Up[10048]   1:51:00
18473        16    12/30/21 8:00      Go To Logout[10025]   0:02:00
18474        16    12/30/21 8:00             Lunch[10001]   0:31:00
18475        16    12/30/21 8:00       Outbound Calls[32]   0:38:00
18476        16    12/30/21 8:00             Undefined[0]   0:56:00

[18477 rows x 4 columns]

### Remove unnecessary values

In [191]:
# Check reason code values
Not_Ready_df['REASON_CODE'].value_counts()

Undefined[0]                 3952
Go To Logout[10025]          3117
Break[10003]                 2908
Extended Wrap Up[10048]      2878
Lunch[10001]                 2133
RONA[32767]                  1027
Administration[11043]         817
[50003]                       449
Outbound Calls[32]            379
Computer Issues[10030]        228
Meeting[10007]                224
Training[10005]               171
CTI Failure[50002]             74
Member Facing Work[11494]      61
[999]                          50
[32762]                         8
Missed Tasks[50010]             1
Name: REASON_CODE, dtype: int64

In [192]:
# Remove unncessary value codes not associated with Not Ready time
Not_Ready_df = Not_Ready_df.loc[(Not_Ready_df['REASON_CODE'] != 'Undefined[0]')
            & (Not_Ready_df['REASON_CODE'] != '[50003]') & (Not_Ready_df['REASON_CODE'] != '[999]')
            & (Not_Ready_df['REASON_CODE'] != '[32762]') & (Not_Ready_df['REASON_CODE'] != 'CTI Failure[50002]')
            & (Not_Ready_df['REASON_CODE'] != 'Missed Tasks[50010]')]

# Double check reason code values
Not_Ready_df['REASON_CODE'].value_counts()

Go To Logout[10025]          3117
Break[10003]                 2908
Extended Wrap Up[10048]      2878
Lunch[10001]                 2133
RONA[32767]                  1027
Administration[11043]         817
Outbound Calls[32]            379
Computer Issues[10030]        228
Meeting[10007]                224
Training[10005]               171
Member Facing Work[11494]      61
Name: REASON_CODE, dtype: int64

### Change dtypes

In [193]:
# Check data types
print(Not_Ready_df.dtypes)

Agent_ID             int64
LOG_ON_DATE_TIME    object
REASON_CODE         object
DURATION            object
dtype: object

In [194]:
# Change dtypes
Not_Ready_df['LOG_ON_DATE_TIME'] = pd.to_datetime(Not_Ready_df['LOG_ON_DATE_TIME'])
Not_Ready_df['REASON_CODE'] = Not_Ready_df['REASON_CODE'].astype('string')

print(Not_Ready_df.dtypes)

Agent_ID                     int64
LOG_ON_DATE_TIME    datetime64[ns]
REASON_CODE                 string
DURATION                    object
dtype: object

/var/folders/vw/pd1mjxdd6r72h4pk8h76nhs80000gn/T/ipykernel_2008/2728824376.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Not_Ready_df['LOG_ON_DATE_TIME'] = pd.to_datetime(Not_Ready_df['LOG_ON_DATE_TIME'])
/var/folders/vw/pd1mjxdd6r72h4pk8h76nhs80000gn/T/ipykernel_2008/2728824376.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Not_Ready_df['REASON_CODE'] = Not_Ready_df['REASON_CODE'].astype('string')

In [195]:
# Change DURATION hh:mm:ss format to seconds
Not_Ready_df['DURATION'] = Not_Ready_df['DURATION'].astype('string')

def get_seconds(time_str):
    hh, mm, ss = time_str.split(':')
    return int(hh) * 3600 + int(mm) * 60 + int(ss)

Not_Ready_df['DURATION'] = Not_Ready_df['DURATION'].apply(get_seconds)

print(Not_Ready_df.dtypes)

Not_Ready_df

Agent_ID                     int64
LOG_ON_DATE_TIME    datetime64[ns]
REASON_CODE                 string
DURATION                     int64
dtype: object

/var/folders/vw/pd1mjxdd6r72h4pk8h76nhs80000gn/T/ipykernel_2008/1369183257.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Not_Ready_df['DURATION'] = Not_Ready_df['DURATION'].astype('string')
/var/folders/vw/pd1mjxdd6r72h4pk8h76nhs80000gn/T/ipykernel_2008/1369183257.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Not_Ready_df['DURATION'] = Not_Ready_df['DURATION'].apply(get_seconds)

       Agent_ID    LOG_ON_DATE_TIME              REASON_CODE  DURATION
0            11 2021-01-04 07:47:00             Break[10003]     24720
1            11 2021-01-04 07:47:00  Extended Wrap Up[10048]      6180
2            11 2021-01-04 07:47:00      Go To Logout[10025]       300
3            11 2021-01-04 07:47:00             Lunch[10001]    215400
5             1 2021-01-04 08:27:00             Break[10003]     14940
...         ...                 ...                      ...       ...
18471        16 2021-12-30 08:00:00             Break[10003]     61920
18472        16 2021-12-30 08:00:00  Extended Wrap Up[10048]      6660
18473        16 2021-12-30 08:00:00      Go To Logout[10025]       120
18474        16 2021-12-30 08:00:00             Lunch[10001]      1860
18475        16 2021-12-30 08:00:00       Outbound Calls[32]      2280

[13943 rows x 4 columns]

### Export dataframe to CSV

In [196]:
Not_Ready_df.to_csv('Data/Clean_Agent_Not_Ready_2021.csv', index=False)

## Clean Call Historical Data file

In [204]:
# Read file into dataframe
Call_Type_df = pd.read_csv(calltype_to_load)
Call_Type_df

,CALL_TYPE_NAME,DATE,HOUR,SL,SL_CALLS,SL_CALLS_OFFERED,ABAND_WITHIN_SL,ASA,AHT,ATT,...,Return,Flow Out,Calls Error,Other,PER_QUEUED,PER_ABAN,AV_ABAN_DELAY,SHORT_CALLS,MAX_CALLS_QUEUED,MAX_CALL_WAIT_TIME
0,CN_MIL_DERMA_QUE_CT,1/4/21,8:00 AM,50.00%,1,2,0,0:00:09,0:00:19,0:00:04,...,0,1,0,0.00%,0.00%,33.30%,0:07:02,0,1,0:06:25
1,CN_MIL_DERMA_QUE_CT,1/4/21,9:00 AM,100.00%,1,1,0,0:00:14,0:01:50,0:00:57,...,0,0,0,0.00%,100.00%,0.00%,0:00:00,0,1,0:00:14
2,CN_MIL_DERMA_QUE_CT,1/4/21,10:00 AM,100.00%,2,2,0,0:00:20,0:02:23,0:01:35,...,0,0,0,0.00%,50.00%,0.00%,0:00:00,0,1,0:00:29
3,CN_MIL_DERMA_QUE_CT,1/4/21,11:00 AM,12.50%,1,8,0,0:02:10,0:02:56,0:02:33,...,0,0,0,0.00%,85.70%,0.00%,0:00:00,0,1,0:05:42
4,CN_MIL_DERMA_QUE_CT,1/4/21,12:00 PM,0.00%,0,1,0,0:05:01,0:03:28,0:03:15,...,0,0,0,0.00%,100.00%,0.00%,0:00:00,0,1,0:05:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,SCH_WOMENS_CLINIC_RONA_CT,7/28/21,4:00 PM,100.00%,1,1,0,0:05:53,0:00:43,0:00:02,...,0,0,0,0.00%,100.00%,0.00%,0:00:00,0,1,0:05:53
37576,SCH_WOMENS_CLINIC_RONA_CT,7/29/21,10:00 AM,100.00%,1,1,0,0:01:55,0:00:27,0:00:01,...,0,0,0,0.00%,100.00%,0.00%,0:00:00,0,1,0:01:55
37577,SCH_WOMENS_CLINIC_RONA_CT,8/31/21,9:00 AM,100.00%,1,1,0,0:01:51,0:00:28,0:00:02,...,0,0,0,0.00%,100.00%,0.00%,0:00:00,0,1,0:01:51
37578,SCH_WOMENS_CLINIC_RONA_CT,10/8/21,11:00 AM,100.00%,1,1,0,0:02:01,0:05:55,0:02:32,...,0,0,0,0.00%,100.00%,0.00%,0:00:00,0,1,0:02:01
37579,SCH_WOMENS_CLINIC_RONA_CT,10/13/21,9:00 AM,100.00%,1,1,0,0:00:20,0:01:14,0:00:05,...,0,0,0,0.00%,100.00%,0.00%,0:00:00,0,1,0:00:20

### Remove unnecessary columns

In [205]:
# Show column names for easier copy/paste for column removal
Call_Type_df.columns

Index(['CALL_TYPE_NAME', 'DATE', 'HOUR', 'SL', 'SL_CALLS', 'SL_CALLS_OFFERED',
       'ABAND_WITHIN_SL', 'ASA', 'AHT', 'ATT', 'OFFERED', 'ASSIGNED_FROM_Q',
       'Answered', 'AWT', 'Handled', 'Aband', 'Return', 'Flow Out',
       'Calls Error', 'Other', 'PER_QUEUED', 'PER_ABAN', 'AV_ABAN_DELAY',
       'SHORT_CALLS', 'MAX_CALLS_QUEUED', 'MAX_CALL_WAIT_TIME'],
      dtype='object')

In [206]:
# Remove unnecessary columns
Call_Type_df.drop(columns = ['SL','ASA','ATT','ASSIGNED_FROM_Q','AWT', 'Flow Out', 'Return', 'Calls Error', 'Other',
                             'PER_QUEUED', 'PER_ABAN','AV_ABAN_DELAY', 'SHORT_CALLS',], inplace=True)
Call_Type_df

,CALL_TYPE_NAME,DATE,HOUR,SL_CALLS,SL_CALLS_OFFERED,ABAND_WITHIN_SL,AHT,OFFERED,Answered,Handled,Aband,MAX_CALLS_QUEUED,MAX_CALL_WAIT_TIME
0,CN_MIL_DERMA_QUE_CT,1/4/21,8:00 AM,1,2,0,0:00:19,3,1,1,1,1,0:06:25
1,CN_MIL_DERMA_QUE_CT,1/4/21,9:00 AM,1,1,0,0:01:50,1,1,1,0,1,0:00:14
2,CN_MIL_DERMA_QUE_CT,1/4/21,10:00 AM,2,2,0,0:02:23,2,2,2,0,1,0:00:29
3,CN_MIL_DERMA_QUE_CT,1/4/21,11:00 AM,1,8,0,0:02:56,8,8,7,0,1,0:05:42
4,CN_MIL_DERMA_QUE_CT,1/4/21,12:00 PM,0,1,0,0:03:28,1,1,2,0,1,0:05:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,SCH_WOMENS_CLINIC_RONA_CT,7/28/21,4:00 PM,1,1,0,0:00:43,1,1,1,0,1,0:05:53
37576,SCH_WOMENS_CLINIC_RONA_CT,7/29/21,10:00 AM,1,1,0,0:00:27,1,1,1,0,1,0:01:55
37577,SCH_WOMENS_CLINIC_RONA_CT,8/31/21,9:00 AM,1,1,0,0:00:28,1,1,1,0,1,0:01:51
37578,SCH_WOMENS_CLINIC_RONA_CT,10/8/21,11:00 AM,1,1,0,0:05:55,1,1,1,0,1,0:02:01
37579,SCH_WOMENS_CLINIC_RONA_CT,10/13/21,9:00 AM,1,1,0,0:01:14,1,1,1,0,1,0:00:20

In [207]:
# Check that hours are between 8AM to 5PM
Call_Type_df['HOUR'].value_counts()

10:00 AM    4317
11:00 AM    4271
9:00 AM     4237
2:00 PM     4091
3:00 PM     3963
12:00 PM    3953
4:00 PM     3948
1:00 PM     3939
8:00 AM     3176
5:00 PM     1685
Name: HOUR, dtype: int64

### Change dtypes

In [208]:
# Check data types
print(Call_Type_df.dtypes)

CALL_TYPE_NAME        object
DATE                  object
HOUR                  object
SL_CALLS               int64
SL_CALLS_OFFERED       int64
ABAND_WITHIN_SL        int64
AHT                   object
OFFERED                int64
Answered               int64
Handled                int64
Aband                  int64
MAX_CALLS_QUEUED       int64
MAX_CALL_WAIT_TIME    object
dtype: object

In [209]:
# Change dtypes
Call_Type_df['CALL_TYPE_NAME'] = Call_Type_df['CALL_TYPE_NAME'].astype('string')
Call_Type_df['DATE'] = pd.to_datetime(Call_Type_df['DATE'])

# Change HOUR am/pm time to only show hour in military time
Call_Type_df['HOUR'] = pd.to_datetime(Call_Type_df['HOUR'], format='%I:%M %p').dt.strftime('%H')

# Change AHT hh:mm:ss format to seconds
Call_Type_df['AHT'] = Call_Type_df['AHT'].astype('string')

def get_seconds(time_str):
    hh, mm, ss = time_str.split(':')
    return int(hh) * 3600 + int(mm) * 60 + int(ss)

Call_Type_df['AHT'] = Call_Type_df['AHT'].apply(get_seconds)


# Change MAX_CALL_WAIT_TIME hh:mm:ss format to seconds
Call_Type_df['MAX_CALL_WAIT_TIME'] = Call_Type_df['MAX_CALL_WAIT_TIME'].astype('string')

def get_seconds(time_str):
    hh, mm, ss = time_str.split(':')
    return int(hh) * 3600 + int(mm) * 60 + int(ss)

Call_Type_df['MAX_CALL_WAIT_TIME'] = Call_Type_df['MAX_CALL_WAIT_TIME'].apply(get_seconds)


print(Call_Type_df.dtypes)

Call_Type_df

CALL_TYPE_NAME                string
DATE                  datetime64[ns]
HOUR                          object
SL_CALLS                       int64
SL_CALLS_OFFERED               int64
ABAND_WITHIN_SL                int64
AHT                            int64
OFFERED                        int64
Answered                       int64
Handled                        int64
Aband                          int64
MAX_CALLS_QUEUED               int64
MAX_CALL_WAIT_TIME             int64
dtype: object

,CALL_TYPE_NAME,DATE,HOUR,SL_CALLS,SL_CALLS_OFFERED,ABAND_WITHIN_SL,AHT,OFFERED,Answered,Handled,Aband,MAX_CALLS_QUEUED,MAX_CALL_WAIT_TIME
0,CN_MIL_DERMA_QUE_CT,2021-01-04,08,1,2,0,19,3,1,1,1,1,385
1,CN_MIL_DERMA_QUE_CT,2021-01-04,09,1,1,0,110,1,1,1,0,1,14
2,CN_MIL_DERMA_QUE_CT,2021-01-04,10,2,2,0,143,2,2,2,0,1,29
3,CN_MIL_DERMA_QUE_CT,2021-01-04,11,1,8,0,176,8,8,7,0,1,342
4,CN_MIL_DERMA_QUE_CT,2021-01-04,12,0,1,0,208,1,1,2,0,1,301
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,SCH_WOMENS_CLINIC_RONA_CT,2021-07-28,16,1,1,0,43,1,1,1,0,1,353
37576,SCH_WOMENS_CLINIC_RONA_CT,2021-07-29,10,1,1,0,27,1,1,1,0,1,115
37577,SCH_WOMENS_CLINIC_RONA_CT,2021-08-31,09,1,1,0,28,1,1,1,0,1,111
37578,SCH_WOMENS_CLINIC_RONA_CT,2021-10-08,11,1,1,0,355,1,1,1,0,1,121
37579,SCH_WOMENS_CLINIC_RONA_CT,2021-10-13,09,1,1,0,74,1,1,1,0,1,20

### Group by pod

In [210]:
# Check group name values
Call_Type_df['CALL_TYPE_NAME'].value_counts()

CN_SCH_DERMA_QUE_CT        2510
CN_SCH_SLEEP_QUE_CT        2488
CN_SCH_PAINM_QUE_CT        2478
CN_SCH_ALLGY_QUE_CT        2446
CN_SCH_NEURO_QUE_CT        2428
                           ...
CN_SKP_PULMG_SP_RONA_CT       2
CN_SKP_DERMA_SP_RONA_CT       2
CN_SKP_NEPHR_RONA_CT          2
CN_MIL_DERMA_SP_RONA_CT       1
CN_SCH_NEPHR_SP_RONA_CT       1
Name: CALL_TYPE_NAME, Length: 70, dtype: Int64

In [211]:
# Create a function
def call_fx(x):
    if x.find("DERMA" or "NEPHR" or "NEURO" or "RHEUM") != -1:
        return 'POD 1'
    elif x.find("SLEEP" or "ALLGY" or "PULMG" or "PAINM") != -1:
        return 'POD 2'
    else:
        return 'POD 3'

# Create new column to assign values
Call_Type_df['POD_NAME'] = Call_Type_df['CALL_TYPE_NAME'].apply(call_fx)

Call_Type_df['POD_NAME'].value_counts()

POD 3    28272
POD 1     6154
POD 2     3154
Name: POD_NAME, dtype: int64

In [212]:
# Check each GROUP_NAME value assigned a POD
Call_Type_df['POD_NAME'].isna().sum()

0

### Export dataframe to CSV

In [213]:
Call_Type_df.to_csv('Data/Clean_Call_Type_Historical_2021.csv', index=False)